CREATE TABLE slack_oauth_response (
    created_at timestamptz NOT NULL DEFAULT now(),
    access_token text NOT NULL,
    app_id text NOT NULL,
    authed_user_access_token text NOT NULL,
    authed_user_expires_in int NOT NULL,
    authed_user_id text NOT NULL,
    authed_user_refresh_token text NOT NULL,
    authed_user_scope text NOT NULL,
    authed_user_token_type text NOT NULL,
    bot_user_id text NOT NULL,
    enterprise_id text NOT NULL,
    enterprise_name text NOT NULL,
    error text NOT NULL,
    expires_in int NOT NULL,
    incoming_webhook_channel text NOT NULL,
    incoming_webhook_channel_id text NOT NULL,
    incoming_webhook_configuration_url text NOT NULL,
    incoming_webhook_url text NOT NULL,
    is_enterprise_install bool NOT NULL,
    metadata_cursor text NOT NULL,
    metadata_messages text[] NOT NULL,
    metadata_warnings text[] NOT NULL,
    ok bool NOT NULL,
    refresh_token text NOT NULL,
    scope text NOT NULL,
    team_id text NOT NULL,
    team_name text NOT NULL,
    token_type text NOT NULL
);

