CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TYPE email_status AS ENUM (
    'unverified',
    'active',
    'suspended'
);

CREATE TABLE user_email (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    address text UNIQUE NOT NULL,
    status email_status NOT NULL DEFAULT 'unverified',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE workflow_default (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    namespace text NOT NULL,
    domain text NOT NULL,
    name text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, namespace, "domain", name)
);

