services:
  harness-ui:
    build:
      context: .
      dockerfile: docker/ui
      secrets:
        - netrc
      args:
        PORTAL_VERSION: ${PORTAL_VERSION}
    depends_on:
      - postgres
    ports:
      - "${UI_PORT}:${PORT}"
    environment:
      HARNESS_HTTPSERVER_ADDR: :${PORT}
      HARNESS_HTTPSERVER_KEYROOT: /var/harness/pki
      HARNESS_POSTGRES_DSN: postgresql://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable
    volumes:
      - pki:/var/harness/pki
    networks:
      - backend
  harness-activity:
    build:
      context: .
      dockerfile: docker/activity
      secrets:
        - netrc
      args:
        PORTAL_VERSION: ${PORTAL_VERSION}
    networks:
      - backend
    depends_on:
      - workflow-server
    environment:
      HARNESS_GITLAB_TOKEN: ${HARNESS_GITLAB_TOKEN}
      HARNESS_POSTGRES_DSN: postgresql://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable
      HARNESS_SLACK_CLIENT_ID: ${HARNESS_SLACK_CLIENT_ID}
      HARNESS_SLACK_CLIENT_SECRET: ${HARNESS_SLACK_CLIENT_SECRET}
      HARNESS_SLACK_REDIRECT_URL: https://localhost:${PORT}/slack/oauth/callback
    volumes:
      - /home/jcrabtree/.kube:/home/jcrabtree/.kube
  harness-workflow:
    build:
      context: .
      dockerfile: docker/workflow
      args:
        PORTAL_VERSION: ${PORTAL_VERSION}
    networks:
      - backend
    depends_on:
      - workflow-server
    environment:
      HARNESS_POSTGRES_DSN: postgresql://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable
  workflow-ui:
    image: temporalio/ui:2.39.0
    depends_on:
      - workflow-server
    ports:
      - "${TEMPORALIO_UI_PORT}:8080"
    environment:
      TEMPORAL_ADDRESS: "workflow-server:7233"
      TEMPORAL_CORS_ORIGINS: "http://localhost:8080"
    networks:
      - backend
  workflow-server:
    image: temporalio/auto-setup:${TEMPORALIO_VERSION}
    depends_on:
      - postgres
    environment:
      DB: postgres12
      DB_PORT: ${PGPORT}
      POSTGRES_SEEDS: postgres
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PWD: ${PGPASSWORD}
      DBNAME: temporal
      VISIBILITY_DBNAME: temporal_visibility
    networks:
      - backend
    ports:
      - "${TEMPORALIO_GRPC_PORT}:7233"
      - "${TEMPORALIO_PROMETHEUS_PORT}:9090"
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  psql:
    image: postgres:${POSTGRES_VERSION}
    profiles:
      - jobs
    environment:
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
    networks:
      - backend
    volumes:
      - ./db:/db
    command:
      - "psql"
      - "--pset"
      - "expanded=auto"
      - "-f"
      - "-"
  schema-dump:
    image: postgres:${POSTGRES_VERSION}
    profiles:
      - jobs
    environment:
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
    networks:
      - backend
    command:
      - "pg_dump"
      - "--file"
      - "db/sqlc/schema.sql"
      - "--schema-only"
    volumes:
      - ./db:/db
  migrate:
    profiles:
      - jobs
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./${MIGRATE_PATH}:/${MIGRATE_PATH}
    image: migrate/migrate:${GOMIGRATE_VERSION}
    command: 
      - "-database"
      - "postgresql://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable"
      - "-path"
      - "/${MIGRATE_PATH}"
      - "goto"
      - "${MIGRATE_VERSION}"
  migrate-force:
    profiles:
      - jobs
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./${MIGRATE_PATH}:/${MIGRATE_PATH}
    image: migrate/migrate:${GOMIGRATE_VERSION}
    command: 
      - "-database"
      - "postgresql://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable"
      - "-path"
      - "/${MIGRATE_PATH}"
      - "force"
      - "${MIGRATE_VERSION}"

networks:
  backend:

volumes:
  pgdata:
  pki:

secrets:
  netrc:
    file: /home/jcrabtree/.netrc
