// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_token_by_client_id.sql

package sqlc

import (
	"context"
)

const getUserTokenByClientID = `-- name: GetUserTokenByClientID :one
SELECT
    authed_user_access_token
FROM
    slack_oauth_response
WHERE
    authed_user_id = $1
ORDER BY
    created_at DESC
LIMIT 1
`

// GetUserTokenByClientID fetches the most-recent token for a user id.
func (q *Queries) GetUserTokenByClientID(ctx context.Context, authedUserID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserTokenByClientID, authedUserID)
	var authed_user_access_token string
	err := row.Scan(&authed_user_access_token)
	return authed_user_access_token, err
}
