// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_gitlab_user.sql

package sqlc

import (
	"context"
)

const getGitlabUser = `-- name: GetGitlabUser :one
SELECT
    email
FROM
    gitlab_user_cache
WHERE
    gitlab_user_id = $1
    AND updated_at >= NOW() - INTERVAL '60 days'
`

// GetGitlabUser retrieves a gitlab user from the user cache.
func (q *Queries) GetGitlabUser(ctx context.Context, gitlabUserID int32) (string, error) {
	row := q.db.QueryRow(ctx, getGitlabUser, gitlabUserID)
	var email string
	err := row.Scan(&email)
	return email, err
}
