// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_bot_access_token.sql

package sqlc

import (
	"context"
)

const getBotAccessToken = `-- name: GetBotAccessToken :one
SELECT
    access_token
FROM
    slack_oauth_response
ORDER BY
    created_at DESC
LIMIT 1
`

// GetBotAccessToken fetches the most-recent token for a user id.
func (q *Queries) GetBotAccessToken(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getBotAccessToken)
	var access_token string
	err := row.Scan(&access_token)
	return access_token, err
}
