// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_slack_oauth_response.sql

package sqlc

import (
	"context"
)

const insertSlackOAuthResponse = `-- name: InsertSlackOAuthResponse :exec
INSERT INTO slack_oauth_response (access_token, app_id, authed_user_access_token, authed_user_expires_in, authed_user_id, authed_user_refresh_token, authed_user_scope, authed_user_token_type, bot_user_id, enterprise_id, enterprise_name, error, expires_in, incoming_webhook_channel, incoming_webhook_channel_id, incoming_webhook_configuration_url, incoming_webhook_url, is_enterprise_install, metadata_cursor, metadata_messages, metadata_warnings, ok, refresh_token, scope, team_id, team_name, token_type)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27)
`

type InsertSlackOAuthResponseParams struct {
	AccessToken                     string
	AppID                           string
	AuthedUserAccessToken           string
	AuthedUserExpiresIn             int32
	AuthedUserID                    string
	AuthedUserRefreshToken          string
	AuthedUserScope                 string
	AuthedUserTokenType             string
	BotUserID                       string
	EnterpriseID                    string
	EnterpriseName                  string
	Error                           string
	ExpiresIn                       int32
	IncomingWebhookChannel          string
	IncomingWebhookChannelID        string
	IncomingWebhookConfigurationUrl string
	IncomingWebhookUrl              string
	IsEnterpriseInstall             bool
	MetadataCursor                  string
	MetadataMessages                []string
	MetadataWarnings                []string
	Ok                              bool
	RefreshToken                    string
	Scope                           string
	TeamID                          string
	TeamName                        string
	TokenType                       string
}

// InsertSlackOAuthResponse inserts an oauth response
func (q *Queries) InsertSlackOAuthResponse(ctx context.Context, arg InsertSlackOAuthResponseParams) error {
	_, err := q.db.Exec(ctx, insertSlackOAuthResponse,
		arg.AccessToken,
		arg.AppID,
		arg.AuthedUserAccessToken,
		arg.AuthedUserExpiresIn,
		arg.AuthedUserID,
		arg.AuthedUserRefreshToken,
		arg.AuthedUserScope,
		arg.AuthedUserTokenType,
		arg.BotUserID,
		arg.EnterpriseID,
		arg.EnterpriseName,
		arg.Error,
		arg.ExpiresIn,
		arg.IncomingWebhookChannel,
		arg.IncomingWebhookChannelID,
		arg.IncomingWebhookConfigurationUrl,
		arg.IncomingWebhookUrl,
		arg.IsEnterpriseInstall,
		arg.MetadataCursor,
		arg.MetadataMessages,
		arg.MetadataWarnings,
		arg.Ok,
		arg.RefreshToken,
		arg.Scope,
		arg.TeamID,
		arg.TeamName,
		arg.TokenType,
	)
	return err
}
