// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_user.sql

package sqlc

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" DEFAULT
    VALUES
    RETURNING
        id
`

// InsertUser inserts a new user
func (q *Queries) InsertUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser)
	var id int64
	err := row.Scan(&id)
	return id, err
}
