// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type SlackOauthResponse struct {
	CreatedAt                       pgtype.Timestamptz
	AccessToken                     string
	AppID                           string
	AuthedUserAccessToken           string
	AuthedUserExpiresIn             int32
	AuthedUserID                    string
	AuthedUserRefreshToken          string
	AuthedUserScope                 string
	AuthedUserTokenType             string
	BotUserID                       string
	EnterpriseID                    string
	EnterpriseName                  string
	Error                           string
	ExpiresIn                       int32
	IncomingWebhookChannel          string
	IncomingWebhookChannelID        string
	IncomingWebhookConfigurationUrl string
	IncomingWebhookUrl              string
	IsEnterpriseInstall             bool
	MetadataCursor                  string
	MetadataMessages                []string
	MetadataWarnings                []string
	Ok                              bool
	RefreshToken                    string
	Scope                           string
	TeamID                          string
	TeamName                        string
	TokenType                       string
}
