// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sanity.sql

package sqlc

import (
	"context"
)

const sanity = `-- name: Sanity :exec
SELECT
`

// Sanity runs an empty select statement used to verify connection
func (q *Queries) Sanity(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sanity)
	return err
}
