--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: email_status; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.email_status AS ENUM (
    'unverified',
    'active',
    'suspended'
);


ALTER TYPE public.email_status OWNER TO "user";

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: gitlab_user_cache; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.gitlab_user_cache (
    gitlab_user_id integer NOT NULL,
    email text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.gitlab_user_cache OWNER TO "user";

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    dirty boolean NOT NULL
);


ALTER TABLE public.schema_migrations OWNER TO "user";

--
-- Name: slack_oauth_response; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.slack_oauth_response (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    access_token text NOT NULL,
    app_id text NOT NULL,
    authed_user_access_token text NOT NULL,
    authed_user_expires_in integer NOT NULL,
    authed_user_id text NOT NULL,
    authed_user_refresh_token text NOT NULL,
    authed_user_scope text NOT NULL,
    authed_user_token_type text NOT NULL,
    bot_user_id text NOT NULL,
    enterprise_id text NOT NULL,
    enterprise_name text NOT NULL,
    error text NOT NULL,
    expires_in integer NOT NULL,
    incoming_webhook_channel text NOT NULL,
    incoming_webhook_channel_id text NOT NULL,
    incoming_webhook_configuration_url text NOT NULL,
    incoming_webhook_url text NOT NULL,
    is_enterprise_install boolean NOT NULL,
    metadata_cursor text NOT NULL,
    metadata_messages text[] NOT NULL,
    metadata_warnings text[] NOT NULL,
    ok boolean NOT NULL,
    refresh_token text NOT NULL,
    scope text NOT NULL,
    team_id text NOT NULL,
    team_name text NOT NULL,
    token_type text NOT NULL
);


ALTER TABLE public.slack_oauth_response OWNER TO "user";

--
-- Name: user; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."user" OWNER TO "user";

--
-- Name: user_email; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.user_email (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    address text NOT NULL,
    status public.email_status DEFAULT 'unverified'::public.email_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.user_email OWNER TO "user";

--
-- Name: user_email_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.user_email ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_default; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.workflow_default (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    namespace text NOT NULL,
    domain text NOT NULL,
    name text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.workflow_default OWNER TO "user";

--
-- Name: workflow_default_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.workflow_default ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_default_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gitlab_user_cache gitlab_user_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.gitlab_user_cache
    ADD CONSTRAINT gitlab_user_cache_pkey PRIMARY KEY (gitlab_user_id);


--
-- Name: user_email user_email_address_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.user_email
    ADD CONSTRAINT user_email_address_key UNIQUE (address);


--
-- Name: user_email user_email_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.user_email
    ADD CONSTRAINT user_email_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: workflow_default workflow_default_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.workflow_default
    ADD CONSTRAINT workflow_default_pkey PRIMARY KEY (id);


--
-- Name: workflow_default workflow_default_user_id_namespace_domain_name_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.workflow_default
    ADD CONSTRAINT workflow_default_user_id_namespace_domain_name_key UNIQUE (user_id, namespace, domain, name);


--
-- Name: user_email user_email_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.user_email
    ADD CONSTRAINT user_email_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: workflow_default workflow_default_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.workflow_default
    ADD CONSTRAINT workflow_default_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

