// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upsert_gitlab_user.sql

package sqlc

import (
	"context"
)

const upsertGitlabUser = `-- name: UpsertGitlabUser :exec
INSERT INTO gitlab_user_cache (gitlab_user_id, email, updated_at)
    VALUES ($1, $2, NOW())
ON CONFLICT (gitlab_user_id)
    DO UPDATE SET
        email = EXCLUDED.email,
        updated_at = NOW()
`

type UpsertGitlabUserParams struct {
	GitlabUserID int32
	Email        string
}

// UpsertGitlabUser upserts a gitlab user
func (q *Queries) UpsertGitlabUser(ctx context.Context, arg UpsertGitlabUserParams) error {
	_, err := q.db.Exec(ctx, upsertGitlabUser, arg.GitlabUserID, arg.Email)
	return err
}
