// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upsert_user_email.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUserEmail = `-- name: UpsertUserEmail :one
INSERT INTO user_email (user_id, address, status, updated_at)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (gitlab_user_id)
    DO UPDATE SET
        user_id = EXCLUDED.user_id,
        address = EXCLUDED.address,
        status = EXCLUDED.status,
        updated_at = NOW()
    RETURNING
        id
`

type UpsertUserEmailParams struct {
	UserID    int64
	Address   string
	Status    EmailStatus
	UpdatedAt pgtype.Timestamptz
}

// UpsertUserEmail upserts a user email
func (q *Queries) UpsertUserEmail(ctx context.Context, arg UpsertUserEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserEmail,
		arg.UserID,
		arg.Address,
		arg.Status,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
